In [1]:
from neo4j import GraphDatabase
import pandas as pd
from dotenv import load_dotenv
from glob import glob
import re
import os
import numpy as np
from tqdm import tqdm
from uuid import uuid5, NAMESPACE_URL

In [2]:
load_dotenv()

True

In [3]:
pattern = "out/sab/(?P<SAB>.*)\.(?P<node_type>.+)\.nodes\.csv"
node_types = {}
for filename in tqdm(glob('out/sab/*.nodes.csv')):
	node_type = re.match(pattern, filename).groupdict()['node_type']
	if node_type not in node_types:
		node_types[node_type] = []
	node_types[node_type].append(filename)

100%|██████████| 84/84 [00:00<00:00, 69245.58it/s]

In [4]:
node_ids = {}
for k,v in node_types.items():
	node_ids[k] = set()
	for filename in v:
		df = pd.read_csv(filename, index_col=0)
		node_ids[k] = node_ids[k].union(df.index)

In [5]:
all_nodes = set()
for k,v in node_ids.items():
	all_nodes = all_nodes.union(v)
len(all_nodes)

7505950

In [6]:
nodes = {}
for node_type_a, ids_a in node_ids.items():
	for node_type_b, ids_b in node_ids.items():
		if node_type_a != node_type_b:
			intersect = ids_a.intersection(ids_b)
			if len(intersect):
				node_ids[node_type_a] = node_ids[node_type_a] - intersect
				node_ids[node_type_b] = node_ids[node_type_b] - intersect
				nodes[(node_type_a, node_type_b)] = intersect
				print((node_type_a, node_type_b), len(intersect))

('Gene', 'Metabolite') 1
('Anatomy', 'Disease or Phenotype') 1
('Anatomy', 'Biofluid') 5
('Compound', 'Metabolite') 1403
('PATO', 'Sex') 2

In [7]:
for k,v in node_ids.items():
	nodes[(k)] = v

In [8]:
all_nodes = set()
for k,v in nodes.items():
	print(k)
	all_nodes = all_nodes.union(v)

('Gene', 'Metabolite')
('Anatomy', 'Disease or Phenotype')
('Anatomy', 'Biofluid')
('Compound', 'Metabolite')
('PATO', 'Sex')
Glytoucan
Glycoprotein
Isoform
Protein
4DN File
Gene
MOTRPAC
Anatomy
GlyGen Location
SO
ILX
Amino Acid
Compound
HSCLO
Metabolite
Glycoprotein Citation
PATO
MSIGDB
EXPBINS
NIFSTD
GTEXPVALUEBIN
GlyGen Residue
Disease or Phenotype
exRNA Loci
4DN QVal Bin
Biofluid
GO
Glycan Motif
Assay
Regulatory Element Activity
Glycoprotein Evidence
Taxon
ENCODE CCRE Data Matrix
Glycosyltransferase Reaction
Glycosylation
KFPT
GTEXEQTL
KFGENEBIN
GP ID2PRO
GlyGen src
GlyGen Glycosequence
KFCOHORT
Sex
CLINGEN ALLELE REGISTRY
4DN Loop
ENCODE CCRE
GTEXEXP
4DN Dataset
Glycosylation Site

In [9]:
len(all_nodes)

7505950

In [10]:
len(nodes)

54

In [11]:
os.getenv('NEO4J_URL')

'bolt://localhost:7687'

In [12]:
def index_nodes(node_type, name):
	with GraphDatabase.driver(os.getenv('NEO4J_URL'), auth=(os.getenv('NEO4J_USER'), os.getenv('NEO4J_PASSWORD'))) as driver:
		with driver.session(database="neo4j") as session:
			tx = session.begin_transaction()
			try:
				tx.run("CREATE CONSTRAINT distillery_unique_id_%s IF NOT EXISTS  FOR (n:%s) REQUIRE n.id IS UNIQUE"%(name, node_type))
				tx.run("CREATE INDEX distillery_index_id_%s IF NOT EXISTS  FOR (n:%s) ON (n.id)"%(name, node_type))
				tx.run("CREATE INDEX distillery_index_label_%s IF NOT EXISTS  FOR (n:%s) ON (n.label)"%(name, node_type))
				tx.commit()
			except Exception as e:
				print(e)
				tx.rollback()
			finally:
				tx.close()

In [13]:
for node_type in node_types:
	n = node_type
	if len(node_type.split(" ")) > 1:
		n = "`%s`"%node_type
	index_nodes(n, node_type.replace(" ", "_"))

In [14]:
def ingest_node(node_type, nodes, limit=10000):
	success = True
	with GraphDatabase.driver(os.getenv('NEO4J_URL'), auth=(os.getenv('NEO4J_USER'), os.getenv('NEO4J_PASSWORD'))) as driver:
		with driver.session(database="neo4j") as session:
			skip = 0
			print("Ingesting: %s"%(", ".join(node_type)))
			while skip < len(nodes):
				batch = nodes[skip: skip+limit]
				tx = session.begin_transaction()
				try:
					query = '''
						UNWIND $batch as map
						CREATE (n:%s)
						SET n = map
					'''%(":".join(node_type))
					tx.run(query, {"batch": batch})
					skip += limit
					tx.commit()
				except Exception as e:
					print("Error rolling back...")
					print("Exception", e)
					tx.rollback()
					success = False
					break
				finally:
					tx.close()
			else:
				success = True			
	return success

In [15]:

for node_type, node_ids in nodes.items():
	node_type = node_type if type(node_type) == tuple else [node_type]
	node_dict = {}
	for t in node_type:
		filenames = node_types[t]
		for file in filenames:
			df = pd.read_csv(file, index_col=0).astype(str)
			idx = list(node_ids.intersection(df.index))
			df = df.loc[idx]
			for k,row in df.iterrows():
				v = {}
				for i,j in row.items():
					if type(j) == str:
						v[i] = j
					elif not np.isnan(j):
						v[i] = int(j)
				if k not in node_dict:
					node_dict[k] = {
						"id": k,
						**v
					}
				else:
					node_dict[k] = {
						**node_dict[k],
						**v
					}
	n = []
	for i in node_type:
		if len(i.split(" ")) > 1:
			n.append("`%s`"%i)
		else:
			n.append(i)
	
	r = ingest_node(n, list(node_dict.values()))
	if not r:
		break

Ingesting: Gene, Metabolite
Ingesting: Anatomy, `Disease or Phenotype`
Ingesting: Anatomy, Biofluid
Ingesting: Compound, Metabolite
Ingesting: PATO, Sex
Ingesting: Glytoucan
Ingesting: Glycoprotein
Ingesting: Isoform
Ingesting: Protein
Ingesting: `4DN File`
Ingesting: Gene
Ingesting: MOTRPAC
Ingesting: Anatomy
Ingesting: `GlyGen Location`
Ingesting: SO
Ingesting: ILX
Ingesting: `Amino Acid`
Ingesting: Compound
Ingesting: HSCLO
Ingesting: Metabolite
Ingesting: `Glycoprotein Citation`
Ingesting: PATO
Ingesting: MSIGDB
Ingesting: EXPBINS
Ingesting: NIFSTD
Ingesting: GTEXPVALUEBIN
Ingesting: `GlyGen Residue`
Ingesting: `Disease or Phenotype`
Ingesting: `exRNA Loci`
Ingesting: `4DN QVal Bin`
Ingesting: Biofluid
Ingesting: GO
Ingesting: `Glycan Motif`
Ingesting: Assay
Ingesting: `Regulatory Element Activity`
Ingesting: `Glycoprotein Evidence`
Ingesting: Taxon
Ingesting: `ENCODE CCRE Data Matrix`
Ingesting: `Glycosyltransferase Reaction`
Ingesting: Glycosylation
Ingesting: KFPT
Ingesting: GTEXEQTL
Ingesting: KFGENEBIN
Ingesting: `GP ID2PRO`
Ingesting: `GlyGen src`
Ingesting: `GlyGen Glycosequence`
Ingesting: KFCOHORT
Ingesting: Sex
Ingesting: `CLINGEN ALLELE REGISTRY`
Ingesting: `4DN Loop`
Ingesting: `ENCODE CCRE`
Ingesting: GTEXEXP
Ingesting: `4DN Dataset`
Ingesting: `Glycosylation Site`

In [93]:
pattern = "out/sab/(?P<SAB>.*)\.(?P<node_type>.+)\.nodes\.csv"
node_sabs = {}
for filename in glob('out/sab/*.nodes.csv'):
	sab = re.match(pattern, filename).groupdict()['SAB']
	print(sab)
	if sab not in node_sabs:
		node_sabs[sab] = []
	node_sabs[sab].append(filename)

GLYCANS
PROTEOFORM
PROTEOFORM
PROTEOFORM
IDGP
4DN
ERCCRBP
MOTRPAC
4DN
KF
PROTEOFORM
NPO
NPO
PROTEOFORM
CLINVAR
LINCS
NPO
GTEXEXP
GTEXEQTL
GTEXEXP
MW
PROTEOFORM
NPO
HMAZ
MSIGDB
GTEXEXP
GTEXEQTL
NPO
GTEXEQTL
GLYCANS
LINCS
CLINVAR
ERCCRBP
4DN
PROTEOFORM
ERCCRBP
HGNCHPO
NPO
GLYCANS
4DN
ERCCREG
HMAZ
ERCCRBP
PROTEOFORM
MOTRPAC
NPO
ERCCREG
ERCCREG
NPO
ERCCREG
IDGD
MOTRPAC
GLYCANS
GLYCANS
IDGP
KF
GTEXEQTL
KF
PROTEOFORM
ARCHS4
GLYCANS
IDGD
GLYCANS
KF
4DN
GTEXEQTL
GLYCANS
ERCCREG
MSIGDB
MOTRPAC
MW
MW
ERCCREG
NPO
4DN
AZ
NPO
HGNCUNIPROT
ERCCREG
MW
KF
HGNCHPO
hgnc_enzyme
GTEXEXP
HGNCUNIPROT
4DN
PROTEOFORM

In [66]:
def ingest_edges(relation, meta, source, target, edges, limit=10000):
	success = True
	with GraphDatabase.driver(os.getenv('NEO4J_URL'), auth=(os.getenv('NEO4J_USER'), os.getenv('NEO4J_PASSWORD'))) as driver:
		with driver.session(database="neo4j") as session:
			skip = 0
			while skip < len(edges):
				batch = edges[skip: skip+limit]
				tx = session.begin_transaction()
				try:
					query = '''
						UNWIND $batch as row
						MATCH (n:%s), (m:%s)
						WHERE n.id=row.source and m.id=row.target
						CREATE (n)-[r:%s {
							%s
						}]->(m)

					'''%(source, target, relation, meta)
					tx.run(query, {"batch": batch})
					skip += limit
					tx.commit()
				except Exception as e:
					print("Error rolling back...")
					print("Exception", e)
					tx.rollback()
					success = False
					break
				finally:
					tx.close()
			else:
				success = True			
	return success

In [18]:
import csv

In [19]:
edge_pattern = "out/sab/(?P<SAB>.*)\.edges\.csv"
success = True
for filename in glob('out/sab/*.edges.csv'):
	# GET ID TYPES
	sab = re.match(edge_pattern, filename).groupdict()['SAB']
	if not sab == 'ARCHS4':
		print(sab)
		df = pd.read_csv(filename, index_col=0)
		node_typer = {}
		# if sab == 'HGNCUNIPROT':
		# 	for i in df.source.unique():
		# 		node_typer[i] = 'Gene'
		# 	for i in df.target.unique():
		# 		node_typer[i] = 'Protein'
		# else:
		for f in node_sabs[sab]:
			node_type = re.match(pattern, f).groupdict()['node_type']
			if len(node_type.split(" ")) > 1:
				node_type = "`%s`"%node_type
			with open(f) as o:
				csv_reader = csv.reader(o)
				for row in csv_reader:
					node_typer[row[0]] = node_type
		node_typer = pd.Series(node_typer)
		if len(df.index) != len(set(df.index)):
			df = df.reset_index()
			df = df[[i for i in df.columns if i != "index"]]
		# df["id"] = df.apply(lambda x: str(uuid5(NAMESPACE_URL, "%s_%s_%s_%s"%(x[0], x[2], x[1], x[3]))), axis=1)
		for relation in df.relation.unique():
			edges = []
			d = df[df.relation == relation].dropna(axis=1, how='all')
			source_type = "|".join(node_typer[df.source].unique())
			target_type = "|".join(node_typer[df.target].unique())
			print(source_type, target_type)
			meta = []
			for col in d.columns:
				if (col not in ["source", 'target']):
					meta.append("%s:row.%s"%(col, col))
			edges = list(d.to_dict(orient="index").values())
			print("Ingesting %d %s relation of %s"%(len(edges), relation, sab))
			meta = ",\n".join(meta)
			success = ingest_edges(relation, meta, source_type, target_type, edges)
			if not success:
				break
			if not success:
					break

IDGD
Compound `Disease or Phenotype`
Ingesting 7287 indication relation of IDGD

HGNCHPO
Gene `Disease or Phenotype`
Ingesting 657194 associated_with relation of HGNCHPO
GLYCANS
Glycosylation|`Glycosyltransferase Reaction`|Glytoucan|`GlyGen Residue` Protein|`GlyGen src`|`GlyGen Glycosequence`|Glycosylation|`Glycosyltransferase Reaction`|`Glycan Motif`|`GlyGen Residue`
Ingesting 91 has_enzyme_protein relation of GLYCANS
Glycosylation|`Glycosyltransferase Reaction`|Glytoucan|`GlyGen Residue` Protein|`GlyGen src`|`GlyGen Glycosequence`|Glycosylation|`Glycosyltransferase Reaction`|`Glycan Motif`|`GlyGen Residue`
Ingesting 91 has_enzyme_protein_gr relation of GLYCANS
Glycosylation|`Glycosyltransferase Reaction`|Glytoucan|`GlyGen Residue` Protein|`GlyGen src`|`GlyGen Glycosequence`|Glycosylation|`Glycosyltransferase Reaction`|`Glycan Motif`|`GlyGen Residue`
Ingesting 30986 is_from_source relation of GLYCANS
Glycosylation|`Glycosyltransferase Reaction`|Glytoucan|`GlyGen Residue` Protein|`GlyGen src`|`GlyGen Glycosequence`|Glycosylation|`Glycosyltransferase Reaction`|`Glycan Motif`|`GlyGen Residue`
Ingesting 117146 has_glycosequence relation of GLYCANS
Glycosylation|`Glycosyltransferase Reaction`|Glytoucan|`GlyGen Residue` Protein|`GlyGen src`|`GlyGen Glycosequence`|Glycosylation|`Glycosyltransferase Reaction`|`Glycan Motif`|`GlyGen Residue`
Ingesting 349 attached_by relation of GLYCANS
Glycosylation|`Glycosyltransferase Reaction`|Glytoucan|`GlyGen Residue` Protein|`GlyGen src`|`GlyGen Glycosequence`|Glycosylation|`Glycosyltransferase Reaction`|`Glycan Motif`|`GlyGen Residue`
Ingesting 210563 synthesized_by relation of GLYCANS
Glycosylation|`Glycosyltransferase Reaction`|Glytoucan|`GlyGen Residue` Protein|`GlyGen src`|`GlyGen Glycosequence`|Glycosylation|`Glycosyltransferase Reaction`|`Glycan Motif`|`GlyGen Residue`
Ingesting 19321 has_motif relation of GLYCANS
Glycosylation|`Glycosyltransferase Reaction`|Glytoucan|`GlyGen Residue` Protein|`GlyGen src`|`GlyGen Glycosequence`|Glycosylation|`Glycosyltransferase Reaction`|`Glycan Motif`|`GlyGen Residue`
Ingesting 86033 has_canonical_residue relation of GLYCANS
Glycosylation|`Glycosyltransferase Reaction`|Glytoucan|`GlyGen Residue` Protein|`GlyGen src`|`GlyGen Glycosequence`|Glycosylation|`Glycosyltransferase Reaction`|`Glycan Motif`|`GlyGen Residue`
Ingesting 79 has_parent relation of GLYCANS
KF
KFPT|KFGENEBIN KFCOHORT|`Disease or Phenotype`|Gene
Ingesting 18704 belongs_to_cohort relation of KF
KFPT|KFGENEBIN KFCOHORT|`Disease or Phenotype`|Gene
Ingesting 44611 has_phenotype relation of KF
KFPT|KFGENEBIN KFCOHORT|`Disease or Phenotype`|Gene
Ingesting 13375 gene_has_variants relation of KF
GTEXEQTL
GTEXEQTL Gene|Anatomy|HSCLO|GTEXPVALUEBIN
Ingesting 4522828 located_in relation of GTEXEQTL
GTEXEQTL Gene|Anatomy|HSCLO|GTEXPVALUEBIN
Ingesting 1251403 p_value relation of GTEXEQTL
MOTRPAC
MOTRPAC Gene|Anatomy|Sex
Ingesting 8570 associated_with relation of MOTRPAC
MOTRPAC Gene|Anatomy|Sex
Ingesting 8571 located_in relation of MOTRPAC
MOTRPAC Gene|Anatomy|Sex
Ingesting 8571 sex relation of MOTRPAC
IDGP
Compound Protein
Ingesting 428636 bioactivity relation of IDGP
ERCCREG
Anatomy|`ENCODE CCRE`|`Regulatory Element Activity`|`CLINGEN ALLELE REGISTRY`|GTEXEQTL `Regulatory Element Activity`|Gene|`ENCODE CCRE Data Matrix`|`ENCODE CCRE`|GTEXEQTL
Ingesting 4925800 part_of relation of ERCCREG
Anatomy|`ENCODE CCRE`|`Regulatory Element Activity`|`CLINGEN ALLELE REGISTRY`|GTEXEQTL `Regulatory Element Activity`|Gene|`ENCODE CCRE Data Matrix`|`ENCODE CCRE`|GTEXEQTL
Ingesting 4804247 regulates relation of ERCCREG
Anatomy|`ENCODE CCRE`|`Regulatory Element Activity`|`CLINGEN ALLELE REGISTRY`|GTEXEQTL `Regulatory Element Activity`|Gene|`ENCODE CCRE Data Matrix`|`ENCODE CCRE`|GTEXEQTL
Ingesting 4793066 isa relation of ERCCREG
Anatomy|`ENCODE CCRE`|`Regulatory Element Activity`|`CLINGEN ALLELE REGISTRY`|GTEXEQTL `Regulatory Element Activity`|Gene|`ENCODE CCRE Data Matrix`|`ENCODE CCRE`|GTEXEQTL
Ingesting 63051 located_in relation of ERCCREG
Anatomy|`ENCODE CCRE`|`Regulatory Element Activity`|`CLINGEN ALLELE REGISTRY`|GTEXEQTL `Regulatory Element Activity`|Gene|`ENCODE CCRE Data Matrix`|`ENCODE CCRE`|GTEXEQTL
Ingesting 156836 negatively_regulates relation of ERCCREG
Anatomy|`ENCODE CCRE`|`Regulatory Element Activity`|`CLINGEN ALLELE REGISTRY`|GTEXEQTL `Regulatory Element Activity`|Gene|`ENCODE CCRE Data Matrix`|`ENCODE CCRE`|GTEXEQTL
Ingesting 154093 positively_regulates relation of ERCCREG
4DN
`4DN Dataset`|`4DN File`|`4DN Loop` Assay|Anatomy|`4DN File`|`4DN Loop`|HSCLO|`4DN QVal Bin`
Ingesting 24 has_assay_type relation of 4DN
`4DN Dataset`|`4DN File`|`4DN Loop` Assay|Anatomy|`4DN File`|`4DN Loop`|HSCLO|`4DN QVal Bin`
Ingesting 12 dataset_involves_cell_type relation of 4DN
`4DN Dataset`|`4DN File`|`4DN Loop` Assay|Anatomy|`4DN File`|`4DN Loop`|HSCLO|`4DN QVal Bin`
Ingesting 12 dataset_has_file relation of 4DN
`4DN Dataset`|`4DN File`|`4DN Loop` Assay|Anatomy|`4DN File`|`4DN Loop`|HSCLO|`4DN QVal Bin`
Ingesting 215821 file_has_loop relation of 4DN
`4DN Dataset`|`4DN File`|`4DN Loop` Assay|Anatomy|`4DN File`|`4DN Loop`|HSCLO|`4DN QVal Bin`
Ingesting 215818 loop_us_start relation of 4DN
`4DN Dataset`|`4DN File`|`4DN Loop` Assay|Anatomy|`4DN File`|`4DN Loop`|HSCLO|`4DN QVal Bin`
Ingesting 215822 loop_us_end relation of 4DN
`4DN Dataset`|`4DN File`|`4DN Loop` Assay|Anatomy|`4DN File`|`4DN Loop`|HSCLO|`4DN QVal Bin`
Ingesting 215822 loop_ds_start relation of 4DN
`4DN Dataset`|`4DN File`|`4DN Loop` Assay|Anatomy|`4DN File`|`4DN Loop`|HSCLO|`4DN QVal Bin`
Ingesting 215822 loop_ds_end relation of 4DN
`4DN Dataset`|`4DN File`|`4DN Loop` Assay|Anatomy|`4DN File`|`4DN Loop`|HSCLO|`4DN QVal Bin`
Ingesting 215822 loop_has_qvalue_bin relation of 4DN
LINCS
Compound Compound|Gene
Ingesting 20785 in_similarity_relationship_with relation of LINCS
Compound Compound|Gene
Ingesting 112750 positively_regulates relation of LINCS
Compound Compound|Gene
Ingesting 112759 negatively_regulates relation of LINCS
MW
Anatomy|Gene|Metabolite Metabolite|`Disease or Phenotype`
Ingesting 63964 produces relation of MW
Anatomy|Gene|Metabolite Metabolite|`Disease or Phenotype`
Ingesting 7354 causally_influences relation of MW
Anatomy|Gene|Metabolite Metabolite|`Disease or Phenotype`
Ingesting 4979 correlated_with_condition relation of MW
GTEXEXP
GTEXEXP|Gene EXPBINS|Gene|Anatomy
Ingesting 1573380 has_expression relation of GTEXEXP
GTEXEXP|Gene EXPBINS|Gene|Anatomy
Ingesting 6293520 expressed_in relation of GTEXEXP
CLINVAR
Gene `Disease or Phenotype`
Ingesting 61762 gene_associated_with_disease_or_phenotype relation of CLINVAR
ERCCRBP
Protein|`exRNA Loci` `exRNA Loci`|Biofluid|Gene
Ingesting 462297 molecularly_interacts_with relation of ERCCRBP
Protein|`exRNA Loci` `exRNA Loci`|Biofluid|Gene
Ingesting 268 predicted_in relation of ERCCRBP
Protein|`exRNA Loci` `exRNA Loci`|Biofluid|Gene
Ingesting 116 not_predicted_in relation of ERCCRBP
Protein|`exRNA Loci` `exRNA Loci`|Biofluid|Gene
Ingesting 22092 correlated_in relation of ERCCRBP
Protein|`exRNA Loci` `exRNA Loci`|Biofluid|Gene
Ingesting 102 not_correlated_in relation of ERCCRBP
Protein|`exRNA Loci` `exRNA Loci`|Biofluid|Gene
Ingesting 469588 overlaps relation of ERCCRBP
NPO
Anatomy|NIFSTD|PATO|ILX|Taxon|Compound|Protein|Gene|SO|GO Anatomy|NIFSTD|PATO|Protein|Taxon|Compound|SO|GO|ILX
Ingesting 2639 isa relation of NPO
Anatomy|NIFSTD|PATO|ILX|Taxon|Compound|Protein|Gene|SO|GO Anatomy|NIFSTD|PATO|Protein|Taxon|Compound|SO|GO|ILX
Ingesting 1082 part_of relation of NPO
Anatomy|NIFSTD|PATO|ILX|Taxon|Compound|Protein|Gene|SO|GO Anatomy|NIFSTD|PATO|Protein|Taxon|Compound|SO|GO|ILX
Ingesting 175 contributes_to_morphology_of relation of NPO
Anatomy|NIFSTD|PATO|ILX|Taxon|Compound|Protein|Gene|SO|GO Anatomy|NIFSTD|PATO|Protein|Taxon|Compound|SO|GO|ILX
Ingesting 88 is_part_of relation of NPO
Anatomy|NIFSTD|PATO|ILX|Taxon|Compound|Protein|Gene|SO|GO Anatomy|NIFSTD|PATO|Protein|Taxon|Compound|SO|GO|ILX
Ingesting 1 delineates relation of NPO
Anatomy|NIFSTD|PATO|ILX|Taxon|Compound|Protein|Gene|SO|GO Anatomy|NIFSTD|PATO|Protein|Taxon|Compound|SO|GO|ILX
Ingesting 1 isdelineatedby relation of NPO
Anatomy|NIFSTD|PATO|ILX|Taxon|Compound|Protein|Gene|SO|GO Anatomy|NIFSTD|PATO|Protein|Taxon|Compound|SO|GO|ILX
Ingesting 1 has_role relation of NPO
MSIGDB
MSIGDB Gene
Ingesting 670712 targets_expression_of_gene relation of MSIGDB
MSIGDB Gene
Ingesting 22911 chr_band_contains_gene relation of MSIGDB
MSIGDB Gene
Ingesting 486646 pathway_associated_with_gene relation of MSIGDB
MSIGDB Gene
Ingesting 104759 has_marker_gene relation of MSIGDB
MSIGDB Gene
Ingesting 7321 has_signature_gene relation of MSIGDB
HMAZ
Anatomy Gene
Ingesting 200 has_marker_gene_in_heart relation of HMAZ
Anatomy Gene
Ingesting 485 has_marker_gene_in_kidney relation of HMAZ
Anatomy Gene
Ingesting 225 has_marker_gene_in_liver relation of HMAZ
PROTEOFORM
Protein|Glycoprotein|`Glycoprotein Evidence`|`Glycosylation Site`|`GlyGen Location` Isoform|`Glycoprotein Evidence`|`Glycoprotein Citation`|`GP ID2PRO`|`Glycosylation Site`|`GlyGen Location`|Glytoucan|`Amino Acid`
Ingesting 8404 has_isoform relation of PROTEOFORM
Protein|Glycoprotein|`Glycoprotein Evidence`|`Glycosylation Site`|`GlyGen Location` Isoform|`Glycoprotein Evidence`|`Glycoprotein Citation`|`GP ID2PRO`|`Glycosylation Site`|`GlyGen Location`|Glytoucan|`Amino Acid`
Ingesting 120158 has_evidence relation of PROTEOFORM
Protein|Glycoprotein|`Glycoprotein Evidence`|`Glycosylation Site`|`GlyGen Location` Isoform|`Glycoprotein Evidence`|`Glycoprotein Citation`|`GP ID2PRO`|`Glycosylation Site`|`GlyGen Location`|Glytoucan|`Amino Acid`
Ingesting 61353 sequence relation of PROTEOFORM
Protein|Glycoprotein|`Glycoprotein Evidence`|`Glycosylation Site`|`GlyGen Location` Isoform|`Glycoprotein Evidence`|`Glycoprotein Citation`|`GP ID2PRO`|`Glycosylation Site`|`GlyGen Location`|Glytoucan|`Amino Acid`
Ingesting 2088 citation relation of PROTEOFORM
Protein|Glycoprotein|`Glycoprotein Evidence`|`Glycosylation Site`|`GlyGen Location` Isoform|`Glycoprotein Evidence`|`Glycoprotein Citation`|`GP ID2PRO`|`Glycosylation Site`|`GlyGen Location`|Glytoucan|`Amino Acid`
Ingesting 61353 has_pro_entry relation of PROTEOFORM
Protein|Glycoprotein|`Glycoprotein Evidence`|`Glycosylation Site`|`GlyGen Location` Isoform|`Glycoprotein Evidence`|`Glycoprotein Citation`|`GP ID2PRO`|`Glycosylation Site`|`GlyGen Location`|Glytoucan|`Amino Acid`
Ingesting 52450 glycosylated_at relation of PROTEOFORM
Protein|Glycoprotein|`Glycoprotein Evidence`|`Glycosylation Site`|`GlyGen Location` Isoform|`Glycoprotein Evidence`|`Glycoprotein Citation`|`GP ID2PRO`|`Glycosylation Site`|`GlyGen Location`|Glytoucan|`Amino Acid`
Ingesting 52450 location relation of PROTEOFORM
Protein|Glycoprotein|`Glycoprotein Evidence`|`Glycosylation Site`|`GlyGen Location` Isoform|`Glycoprotein Evidence`|`Glycoprotein Citation`|`GP ID2PRO`|`Glycosylation Site`|`GlyGen Location`|Glytoucan|`Amino Acid`
Ingesting 44763 has_saccharide relation of PROTEOFORM
Protein|Glycoprotein|`Glycoprotein Evidence`|`Glycosylation Site`|`GlyGen Location` Isoform|`Glycoprotein Evidence`|`Glycoprotein Citation`|`GP ID2PRO`|`Glycosylation Site`|`GlyGen Location`|Glytoucan|`Amino Acid`
Ingesting 52450 has_amino_acid relation of PROTEOFORM
AZ
Anatomy Anatomy
Ingesting 165 isa relation of AZ
Anatomy Anatomy
Ingesting 159 located_in relation of AZ

In [63]:
meta

NameError: name 'meta' is not defined

In [20]:
node_sabs.keys()

dict_keys(['GLYCANS', 'PROTEOFORM', 'IDGP', '4DN', 'ERCCRBP', 'MOTRPAC', 'KF', 'NPO', 'CLINVAR', 'LINCS', 'GTEXEXP', 'GTEXEQTL', 'MW', 'HMAZ', 'MSIGDB', 'HGNCHPO', 'ERCCREG', 'IDGD', 'ARCHS4', 'AZ'])

In [21]:
df = pd.read_csv(filename, index_col=0)
df.head()

,source,target,relation,SAB,evidence_class,dcc
0,0480457d-0b0c-5f92-b3d2-08740040ea31,b2d2542f-e7a5-55dd-bca4-97c5e5b949e4,isa,AZ,NaN,HuBMAP
1,d96dc75c-ba4d-5076-b1cd-f48117d47f4e,b2d2542f-e7a5-55dd-bca4-97c5e5b949e4,isa,AZ,NaN,HuBMAP
2,6065a15f-c52b-5a16-a322-7635c54f0655,d96dc75c-ba4d-5076-b1cd-f48117d47f4e,isa,AZ,NaN,HuBMAP
3,297f6f70-21dc-5c8d-892c-82a02d4eacba,d96dc75c-ba4d-5076-b1cd-f48117d47f4e,isa,AZ,NaN,HuBMAP
4,d6780970-f65c-5b2a-8e3b-9a3cc07ea403,d96dc75c-ba4d-5076-b1cd-f48117d47f4e,isa,AZ,NaN,HuBMAP

In [ ]:
edge_pattern = "out/sab/(?P<SAB>.*)\.edges\.csv"
success = True
for filename in glob('out/sab/*.edges.csv'):
	# GET ID TYPES
	sab = re.match(edge_pattern, filename).groupdict()['SAB']
	print(sab)
	node_typer = {}
	for f in node_sabs[sab]:
		node_type = re.match(pattern, f).groupdict()['node_type']
		if len(node_type.split(" ")) > 1:
			node_type = "`%s`"%node_type
		with open(f) as o:
			csv_reader = csv.reader(o)
			for row in csv_reader:
				node_typer[row[0]] = node_type
	node_typer = pd.Series(node_typer)
	df = pd.read_csv(filename, index_col=0)
	if len(df.index) != len(set(df.index)):
		df = df.reset_index()
		df = df[[i for i in df.columns if i != "index"]]
	# df["id"] = df.apply(lambda x: str(uuid5(NAMESPACE_URL, "%s_%s_%s_%s"%(x[0], x[2], x[1], x[3]))), axis=1)
	for relation in df.relation.unique():
		try:
			edges = []
			d = df[df.relation == relation].dropna(axis=1, how='all')
			source_type = "|".join(node_typer[df.source].unique())
			target_type = "|".join(node_typer[df.target].unique())
			print(source_type, target_type)
		except Exception as e:
			print(e)
	# 	meta = []
	# 	for col in d.columns:
	# 		if (col not in ["source", 'target']):
	# 			meta.append("%s:row.%s"%(col, col))
	# 	edges = list(d.to_dict(orient="index").values())
	# 	print("Ingesting %d %s relation of %s"%(len(edges), relation, sab))
	# 	meta = ",\n".join(meta)
	# 	success = ingest_edges(relation, meta, source_type, target_type, edges)
	# 	if not success:
	# 		break
	# if not success:
	# 		break

In [22]:
total_edges = 0
for filename in glob('out/sab/*.edges.csv'):
	df = pd.read_csv(filename, index_col=0)
	total_edges += df.shape[0]
total_edges

34872802

In [ ]:
# with GraphDatabase.driver(os.getenv('NEO4J_URL'), auth=(os.getenv('NEO4J_USER'), os.getenv('NEO4J_PASSWORD'))) as driver:
# 		with driver.session(database="neo4j") as session:
# 			tx = session.begin_transaction()
# 			try:
# 				tx.run("CREATE CONSTRAINT distillery_unique_id_%s IF NOT EXISTS  FOR (n:%s) REQUIRE n.id IS UNIQUE"%(name, node_type))
# 				tx.run("CREATE INDEX distillery_index_id_%s IF NOT EXISTS  FOR (n:%s) ON (n.id)"%(name, node_type))
# 				tx.run("CREATE INDEX distillery_index_label_%s IF NOT EXISTS  FOR (n:%s) ON (n.label)"%(name, node_type))
# 				tx.commit()
# 			except Exception as e:
# 				print(e)
# 				tx.rollback()
# 			finally:
# 				tx.close()

In [23]:
with GraphDatabase.driver(os.getenv('NEO4J_URL'), auth=(os.getenv('NEO4J_USER'), os.getenv('NEO4J_PASSWORD'))) as driver:
		with driver.session(database="neo4j") as session:
			tx = session.begin_transaction()
			record = tx.run("MATCH (a:Gene) RETURN a LIMIT 10")
			for i in record:
				a = i['a']

In [24]:
a.items()

dict_items([('HGNC', '48557'), ('ENSEMBL', 'ENSG00000223247'), ('OMIM', 'nan'), ('label', 'RNU2-64P'), ('id', 'df7e9532-02d7-5ffa-9f04-7f839aaa4623'), ('type', 'Gene'), ('ENTREZ', 'nan')])

In [3]:
enzyme_genes = pd.read_csv('../dd_data/HGNC_genes.txt', sep="\t", index_col=0)

In [4]:
enzyme_genes.head()

,Status,Approved symbol,Approved name,Enzyme (EC) ID,UniProt accession
HGNC ID,,,,,
HGNC:5,Approved,A1BG,alpha-1-B glycoprotein,NaN,P04217
HGNC:37133,Approved,A1BG-AS1,A1BG antisense RNA 1,NaN,NaN
HGNC:24086,Approved,A1CF,APOBEC1 complementation factor,NaN,Q9NQ94
HGNC:7,Approved,A2M,alpha-2-macroglobulin,NaN,P01023
HGNC:27057,Approved,A2M-AS1,A2M antisense RNA 1,NaN,NaN

In [10]:
enzyme_ids = [i.split(":")[1] for i in enzyme_genes[~enzyme_genes['Enzyme (EC) ID'].isna()].index]
len(enzyme_ids)

2022

In [11]:
enzyme_ids[0]

'18149'

In [12]:
records = []
with GraphDatabase.driver(os.getenv('NEO4J_URL'), auth=(os.getenv('NEO4J_USER'), os.getenv('NEO4J_PASSWORD'))) as driver:
	with driver.session(database="neo4j") as session:
		tx = session.begin_transaction()
		record = tx.run('''
			UNWIND $batch as row
			MATCH (a:Gene)
			WHERE a.HGNC = row	
			RETURN a   
		''', batch=enzyme_ids)
		
		for i in record:
			records.append(i)

In [13]:
len(records)

2021

In [14]:
recs = []
for i in records:
	recs.append(i["a"]["HGNC"])

## Add Enzyme

In [15]:
records = []
with GraphDatabase.driver(os.getenv('NEO4J_URL'), auth=(os.getenv('NEO4J_USER'), os.getenv('NEO4J_PASSWORD'))) as driver:
	with driver.session(database="neo4j") as session:
		tx = session.begin_transaction()
		tx.run('''
			UNWIND $batch as row
			MATCH (a:Gene)
			WHERE a.HGNC = row	
			set a :Enzyme
		''', batch=enzyme_ids)
		tx.commit()

In [16]:
records = []
with GraphDatabase.driver(os.getenv('NEO4J_URL'), auth=(os.getenv('NEO4J_USER'), os.getenv('NEO4J_PASSWORD'))) as driver:
	with driver.session(database="neo4j") as session:
		tx = session.begin_transaction()
		results = tx.run('''
			MATCH (a:Enzyme)
			return a
		''')
		for i in results:
			records.append(i)

In [17]:
len(records)

1889

In [18]:
records[0]['a'].items()

dict_items([('HGNC', '30045'), ('NCI', 'nan'), ('ENSEMBL', 'ENSG00000157106'), ('OMIM', '607032.0'), ('ORDO', 'nan'), ('label', 'SMG1'), ('id', '968fc3c6-d15f-5b79-860f-d5544db78fe1'), ('ENTREZ', '23049.0'), ('type', 'Gene')])

In [19]:
recs = {}
for i in records:
	vals = {}
	for k,v in i['a'].items():
		if (k != 'id'):
			vals[k] = v
	recs[i['a']['id']] = vals

In [20]:
len(recs)

1889

In [21]:
df = pd.DataFrame.from_dict(recs, orient="index")

In [22]:
df

,HGNC,NCI,ENSEMBL,OMIM,ORDO,label,ENTREZ,type
968fc3c6-d15f-5b79-860f-d5544db78fe1,30045,nan,ENSG00000157106,607032.0,nan,SMG1,23049.0,Gene
b44b0e4f-a5e4-5dca-88d9-0bcbe1b9669b,1516,nan,ENSG00000121691,115500.0,119192.0,CAT,847.0,Gene
ead645df-7a15-5e10-936c-daa6adb71135,6823,nan,ENSG00000177239,604346.0,279756.0,MAN1B1,11253.0,Gene
8955fa30-f979-5b4a-a249-d10c0227a14b,4693,nan,ENSG00000143774,139270.0,nan,GUK1,2987.0,Gene
13bda49b-b9c8-596c-93aa-73c36dfae9f8,20454,nan,ENSG00000125630,602000.0,597004.0,POLR1B,84172.0,Gene
...,...,...,...,...,...,...,...,...
bea454f1-f91b-5117-a394-541190004e11,4686,nan,ENSG00000123201,nan,nan,GUCY1B2,2974.0,Gene
af8b451f-0138-5b0e-b11e-9aea96ee25ff,16431,NaN,ENSG00000093134,NaN,NaN,VNN3P,55350.0,Gene
8b10293c-7ca7-591e-9b1f-83cb7cbb0c68,14922,NaN,ENSG00000127252,NaN,NaN,PLAAT1,57110.0,Gene
0159c394-4216-56de-bd5e-c85e13804696,24978,NaN,ENSG00000168004,NaN,NaN,PLAAT5,117245.0,Gene
1de01a1b-dd8c-57d0-87a2-95de543d44e8,4641,nan,nan,600436.0,nan,GSTT1,nan,Gene

In [23]:
df = df[['label', 'type', 'HGNC', 'ENSEMBL', 'OMIM',  'ORDO', 'ENTREZ', 'NCI']]

In [24]:
df.to_csv('out/sab/hgnc_enzyme.Enzyme.nodes.csv')

In [26]:
import csv

In [70]:
mapper = []
with open('../dd_data/idmapping_2023_08_24.tsv') as o:
	csv_reader = csv.reader(o, delimiter="\t")
	header = True
	for row in csv_reader:
		if header:
			header = False
		else:
			mapper.append({
				"protein": row[0],
				"gene": row[1]
			})

In [71]:
for i in mapper:
	i["gene"] = i['gene'].replace('HGNC:',"")

In [72]:
mapper[0]

{'protein': 'A0A087X1C5', 'gene': '2624'}

In [73]:
len(mapper)

20369

In [74]:
proteins = []
with GraphDatabase.driver(os.getenv('NEO4J_URL'), auth=(os.getenv('NEO4J_USER'), os.getenv('NEO4J_PASSWORD'))) as driver:
	with driver.session(database="neo4j") as session:
		tx = session.begin_transaction()
		record = tx.run('''
			UNWIND $batch as row
			MATCH (a:Protein)
			WHERE a.UNIPROTKB = row.protein 
			RETURN a   
		''', batch=mapper)
		
		for i in record:
			proteins.append(i)
len(proteins)

8381

In [75]:
genes = []
with GraphDatabase.driver(os.getenv('NEO4J_URL'), auth=(os.getenv('NEO4J_USER'), os.getenv('NEO4J_PASSWORD'))) as driver:
	with driver.session(database="neo4j") as session:
		tx = session.begin_transaction()
		record = tx.run('''
			UNWIND $batch as row
			MATCH (a:Gene)
			WHERE a.HGNC = row.gene 
			RETURN a   
		''', batch=mapper)
		
		for i in record:
			genes.append(i)
len(genes)

20076

In [76]:
len(proteins)

8381

In [77]:
len(genes)

20076

In [78]:
proteins[0]['a']['UNIPROTKB']

'A0AV96'

In [79]:
protein_id_mapper = {}
protein_label_mapper = {}
for i in proteins:
	protein_id_mapper[i['a']['UNIPROTKB']] = i['a']["id"]
	protein_label_mapper[i['a']['UNIPROTKB']] = i['a']["label"]

In [80]:
gene_id_mapper = {}
gene_label_mapper = {}
for i in genes:
	gene_id_mapper[i['a']['HGNC']] = i['a']["id"]
	gene_label_mapper[i['a']['HGNC']] = i['a']["label"]

In [81]:
protein_gene = pd.read_csv('../dd_data/idmapping_2023_08_24.tsv', sep="\t", index_col=0)

In [82]:
protein_gene.index.name = "protein"
protein_gene.columns = ["gene"]

In [83]:
protein_gene_mapper = protein_gene.to_dict()["gene"]

In [84]:
protein_list = []
gene_list = []
prot_gene = []
for prot, protid in protein_id_mapper.items():
	hgnc = protein_gene_mapper[prot]
	hgnc = hgnc.replace('HGNC:','')
	if hgnc in gene_id_mapper:
		prot_gene.append({
			"source": gene_id_mapper[hgnc],
			"target": protid,
			"relation": "is_protein",
			"sab": "HGNCUNIPROT"
		})
		protein_list.append({
			"id": protid,
			"label": protein_label_mapper[prot],
			"UNIPROTKB": prot
		})
		gene_list.append({
			"id": gene_id_mapper[hgnc],
			"label": gene_label_mapper[hgnc],
			"HGNC": hgnc
		})

In [85]:
len(protein_list), len(gene_list)

(8327, 8327)

In [86]:
df = pd.DataFrame.from_records(prot_gene)

In [87]:
protein_df = pd.DataFrame.from_records(protein_list)
gene_df = pd.DataFrame.from_records(gene_list)

In [88]:
protein_df = protein_df.set_index('id')
gene_df = gene_df.set_index('id')
gene_df.head()

                                      label   HGNC
id
3e46112d-68ba-5e2c-a050-6a51c0a802ef  RBM47  30358
6770e291-189f-54b5-97ca-8494f275bea5   E2F8  24727
e3073526-6a7b-519f-8779-74b174d3f187   UBA6  25581
08b0c19d-7b28-543d-9a17-f1e7f0cb0ba5  ESYT2  22211
ca78a723-4495-5f1a-8ba5-1e9e37792514  SHTN1  29319

In [89]:
protein_df.to_csv("out/sab/HGNCUNIPROT.Protein.nodes.csv")
gene_df.to_csv("out/sab/HGNCUNIPROT.Gene.nodes.csv")

In [90]:
df.to_csv('out/sab/HGNCUNIPROT.edges.csv')

In [91]:
meta = []
for col in df.columns:
	if (col not in ["source", 'target']):
		meta.append("%s:row.%s"%(col, col))
edges = list(df.to_dict(orient="index").values())
meta = ",\n".join(meta)
success = ingest_edges("is_protein", meta, 'Gene', 'Protein', edges)

In [92]:
edges

[{'source': '3e46112d-68ba-5e2c-a050-6a51c0a802ef',
  'target': 'db42d55a-78a9-5cd4-b793-5050727e6763',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '6770e291-189f-54b5-97ca-8494f275bea5',
  'target': '6878c662-f933-5c8c-a495-436023b66003',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': 'e3073526-6a7b-519f-8779-74b174d3f187',
  'target': 'fc5fd09a-de9f-56b8-b2fd-8b853acdfc66',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '08b0c19d-7b28-543d-9a17-f1e7f0cb0ba5',
  'target': 'cd95ba62-e181-5bce-a450-e2aff857ceb2',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': 'ca78a723-4495-5f1a-8ba5-1e9e37792514',
  'target': '905e9ef5-6c6c-5bb1-8b9c-10154f300f77',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '6467c1f9-a486-59bb-a208-266d96edeca5',
  'target': '76c36623-36d4-5f67-8d85-8447b01828b8',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': 'd76c3dca-c82e-51e2-9a43-ad1dfdb8f668',
  'target': 'e24daab0-5b60-56d1-85b6-2a85e174d07b',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '5a451756-53e0-5a29-8cc9-60ad2eb87278',
  'target': '6ab2a0e5-eaed-5378-98ce-271ad3123748',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '0eef8f58-c88e-5980-a89d-b117318fd1e3',
  'target': '2fa84024-0830-5573-bf03-6aed0b918b29',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': 'b7739ff4-2876-5a96-8531-123f892006dd',
  'target': 'd0398f9b-7540-5667-a87e-b6d7689c81ef',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '33fbcffd-d233-5b8f-937a-09d91e49f0fa',
  'target': '740bc21a-6d98-596c-8e61-a7c94c2f3794',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '5c514700-3e28-58cb-be26-a15fcf74fd7e',
  'target': '851d6cb0-ab7e-58af-b369-54472a522056',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': 'af3f996e-0c6b-5abd-ba25-4895e9c899e4',
  'target': 'f2abac30-3192-5b25-893d-1487416f9492',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '474f0ca1-d9b6-5595-9832-43b0751a1430',
  'target': '945e6704-8c79-53b3-bbe8-54648d2f58e1',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '8d0f865e-f110-5f75-9d79-229fc89fc952',
  'target': 'ea458cd6-c61b-50f4-87a1-fd2808fbaad2',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '951a9e9c-3d68-5e3b-826f-5320919ea8ec',
  'target': '101b44b2-8aac-53db-9d32-62e22f4d7aa0',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': 'ad01ce80-2941-5d4c-8537-f0ebeadafdbf',
  'target': 'fa8aebdd-dc0f-5e8f-835c-d7493f144a48',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': 'ea816f50-161a-5c3a-891a-349e12856ae6',
  'target': '8fadea95-b4d1-544b-8c31-ad603455e61d',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': 'e12fbeec-4270-59c2-855f-2520177dcce5',
  'target': 'aaf6d4ae-bd24-5828-825a-b31a94c7977c',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': 'c0644a74-276a-5cd6-ac78-c393347db3cc',
  'target': 'b397a7fb-f983-5268-b751-858b49a7a53f',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '6d3e867a-3ca3-5cab-bef4-226f3358136c',
  'target': '301628c7-3b75-52e3-8b3c-84970200d60a',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': 'fa969e26-86a6-54e7-bb12-43ac41c056bc',
  'target': 'bd8cb2b3-9b04-5083-8385-28efef512d96',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': 'c6a9674c-520c-59cb-8e55-3126cd336075',
  'target': '83458df6-b280-5f82-829b-4e7e8b634b10',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '2d7e86d6-fb54-5c57-8bed-1561e31a718f',
  'target': '3823a74a-6e3a-548d-a6d4-7161e9138ddd',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '070ce82f-5500-53fd-8e5e-f7816f2163a7',
  'target': '84d7980e-75b9-53d9-b41e-f95743ec0620',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': 'f8a192cf-c4e4-539a-8620-6194360fcb1e',
  'target': 'e4c2eb86-4194-514e-9cd2-d6a817e62eae',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': 'b35bb83a-60a1-5bc4-9f65-fb56b616def6',
  'target': '00e6025f-a22a-57a2-9426-14963dfa6371',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '63066e14-f31b-55ee-9913-06cfa1a4913d',
  'target': 'f447c207-2a6f-5e9b-944c-2ada091515d9',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': 'e7a433aa-b915-5693-9da3-84c4be1d90aa',
  'target': '8020c59e-5119-5568-a726-6885c6681b80',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '79be7ced-c259-52a5-b6c2-9b41500a23bb',
  'target': '0a4cc777-af2c-593d-ac89-c0b30c80bf22',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '7c196b8d-87ee-5388-ac31-f017dc766bb5',
  'target': '8e3cd4f5-e9bb-5379-aa6b-5d24eaf7d458',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '08031da4-7411-5737-a456-5489d78d8494',
  'target': 'ab6e62ba-f77c-5a0c-8ff3-83925618654a',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '3d1558aa-a5d1-55f3-8df6-415c128f2f8a',
  'target': '759a1640-2e6b-518d-8baa-69f34d2129b2',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '952352f9-512a-5356-8027-fc23831b7559',
  'target': '5e09b09a-3938-5e41-8503-5a199332250e',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '41c1d77f-da64-5851-a9a1-64b97a2c2755',
  'target': '642a73f5-539f-585c-9919-3519039d8ecd',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '2bbe20b4-cde4-5e77-8c3b-caaa551882e9',
  'target': '94a34140-3f3d-5cf2-9f8a-953c45c877ef',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '0a33a353-eb4d-5329-a044-b218b6f2f981',
  'target': '67c0c79b-938f-5684-b452-d21dbb9fe6da',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': 'a56a96c9-a95a-575a-9e40-fd2e8908a453',
  'target': '1be501bd-c593-5690-ac16-af93965e99a5',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '087bbc76-c56e-5764-b5a1-4ff946e79935',
  'target': 'eed74bf9-5c5a-57a0-9738-58ae043a5214',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '99e46229-1f7c-55cc-b0a1-fe66bb206d7c',
  'target': '8cd2e2ed-3f59-590d-87af-eba526a4a529',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '9a98ec3f-f201-530e-80d1-015c172525fa',
  'target': '58f8fd78-4e3d-55a1-8b31-8d8ec879b2a7',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '092a38ae-2bfb-555a-95e0-1c72a653eb1b',
  'target': 'c591cd22-441c-5a2b-9411-f6916be3d405',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '8344e7d8-5160-5d36-97b9-81690e84a84c',
  'target': 'ced45d87-404a-56d6-bfb2-963625445cc6',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '68f312e6-e74e-56e6-9569-29bd523d0344',
  'target': 'b344b47d-1ee9-5ff0-bdf9-c6d197a7f1be',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '9b6508d7-7f3a-545c-85ee-cb6fe6be2bc1',
  'target': 'f2d9ef10-43dd-55b2-827f-5bb9fc22440a',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '78d44a0e-2576-5779-b0b7-ba9c81c39834',
  'target': '4cbb45e5-98fa-56be-b3d0-1b79873ba5ef',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': 'a905b83d-20d1-5d6f-89d0-1729f4c0d1e7',
  'target': 'b8ebb697-2c3b-548a-a019-77ecdc57f21c',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '59fd6abd-2ba5-5899-9f51-316af3e43bd6',
  'target': 'fe8d1bd7-bf62-5769-b174-d03d412fd7d4',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': 'fb60d0e6-6d92-5485-9c4a-9ffbb28823ca',
  'target': '0b3f31d6-caa4-5bb0-8080-4699839ff69f',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '4b3c00e7-1ed9-5058-b006-d78bd09d28c9',
  'target': '84cce979-7d4c-58fa-a36a-61eb67c6e6d8',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '51e02c71-26c8-5b23-8c40-19f437c88145',
  'target': '88ef44a1-3be5-5067-9f70-f6036c0681d5',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': 'e2ecbe87-afc7-5024-965d-b6baf8b7abde',
  'target': 'd22fbe6c-e931-5281-bf5d-5657594b89b3',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '853a7668-64aa-50b7-83ff-a412d97c5a0e',
  'target': '70278114-b7f8-5bd4-8f0f-449b85995e84',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': 'cb10e05e-ca37-5e61-970f-72003e5c7641',
  'target': '41fe4329-1d00-5786-a333-11d09d97fe9e',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '52b79f21-7e79-5f32-ae7c-667fbf6b8284',
  'target': '59d77e51-de37-55f6-9d9f-81ded4d7ef13',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '4935d3db-71a4-5e58-abbc-463d5a95b6c0',
  'target': 'd9adaaa7-e814-5901-83ad-baf8c7b89702',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '77930272-0d4d-5fab-a03e-fc756cc265f9',
  'target': '16ff943e-b77a-5d58-ab19-8dcb82295bb7',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': 'f04fd7c4-6967-52ca-ab29-24a260ee2f28',
  'target': '39cc8988-d6c8-548f-adf0-28574c77b0f7',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '10059fcd-7065-5723-b8fb-1da3f9082a54',
  'target': 'f46d86bb-4d56-50e9-932a-8d980496cc71',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': 'bfdab539-b3f8-56e5-a55d-f618b72479d6',
  'target': '55308007-6e60-5f54-9a7b-9e46ed65ade5',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '51b23c18-b453-50b9-9cf2-a585c26a4243',
  'target': '6f89b16c-9802-574c-beb6-6407004f990d',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '0749bd8b-3b74-50cf-be56-d085ad56061c',
  'target': '797b4947-f595-569b-b527-e8089f8b7c7d',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '98c780be-ec29-5df6-98fa-f4c93d69ffee',
  'target': 'dcb53677-0170-5287-b7aa-fe4476e8daab',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '2b17c5ca-398d-52f0-b148-a38a608869e3',
  'target': '27f75113-f4a2-5b6f-8d13-c35c3860a289',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': 'ba79d0c9-7aa3-57c0-b574-b32c69cf64d4',
  'target': '7b89ad9d-06d1-5c58-96d4-4b7888e45ca0',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': 'c92ba324-6269-5e86-9e33-ff29a4a80f87',
  'target': 'fb256589-1ca4-5ba3-802e-ec0e45db740c',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '4a4a3028-d8c1-5079-8011-04b999c3d89a',
  'target': '0aee10b9-5900-52a8-97f5-0ab47d2744e2',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '2240b817-844c-58b4-ab62-5dd5624f2c14',
  'target': '36009f68-6903-5264-b5cf-8c9b5ce8d29f',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': 'a962a5a4-82c5-59db-a47b-8f67945e623c',
  'target': '770cffc1-8cf9-559c-89ed-9d796d67d9b7',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': 'ebfec1e6-fbae-59f3-823b-4472b6d8823b',
  'target': 'e538ce82-4c0a-52b0-85a4-903cbcbaa773',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': 'dafbcfbd-8e53-5bd6-bc5f-fc0c410d6283',
  'target': '52807244-be94-5cf2-99a8-70f2f046b6cd',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '64ad9cf1-ce95-57ea-ba57-3fae705a7417',
  'target': '9b9a48f6-0d80-54cc-873d-6a81c9418199',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '7e83dc2e-ac64-5b3c-9e62-20497e81469e',
  'target': '5e82da2d-3f57-5a3e-be67-3229e555ca1e',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': 'd778fb47-f67f-5925-a394-70707b40e65d',
  'target': '41457021-bcf7-5e5e-810c-d093907dfbdc',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '37bb7c85-3af0-5a27-a277-20e32fa96485',
  'target': '229b3d7f-ae86-5615-abc9-013c615181ab',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '736dd34c-07ff-5ee1-8b54-95050c870c85',
  'target': 'b7ccb089-b3bb-58e7-b5b9-947cd9653138',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': 'd86cb0e1-50fb-57ef-8266-e1375999a265',
  'target': '9f2b9382-7f97-5867-a462-9e648bf99fee',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '8af64a5b-79d6-52e8-a346-e4ae9dfa1819',
  'target': 'ab58cff1-3f7f-5015-bcf8-bcc7efc91213',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '1b205316-33f8-5022-a7e9-ead3c14dae8d',
  'target': 'd19bc534-e239-53a4-be86-f53deaf7744a',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '4492a166-59df-5ff6-ad3c-6fd0477e5870',
  'target': '02f8a465-1e2e-53e4-b83c-3ef1ffc7dd04',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '1c48bf1a-ffda-5291-a158-931106c9f028',
  'target': '8a0a9205-b72f-5e5b-8a15-586dbe5cd285',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '65d0d76b-d8b3-5ae0-80e4-588d0613bf26',
  'target': 'eeddff3e-0c78-536d-a4b4-5e35cd9383d2',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '50241f3a-0110-5a17-b8b3-fd653eb25d5b',
  'target': '73505ab6-6ca3-52f2-9c6b-1f1111706446',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '7d28da41-0eb9-550f-9bf2-d0d0d1ce7852',
  'target': 'f1f5bb97-308d-579e-9620-18366ba6c57e',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '39e744ec-81ae-52bd-9530-41631bde8527',
  'target': '67dcfcc2-8975-5ef0-800e-fd0dcc86ff85',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '56202e98-08b6-5644-a67a-4f4aa5db8813',
  'target': 'b498aa09-59fd-500f-865a-4ca5a8b3afed',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '60ae2434-aaac-5152-a5d8-5cd6a7223f53',
  'target': 'c9f2bf66-1f14-5381-9f7c-94531ba30f92',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': 'cc3a67f2-70b2-5ccd-bdaa-e6610795dc95',
  'target': '8ba28606-a052-5645-be8a-344498be483e',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '5c01f06a-8ff0-5b09-b0c6-6ed8f3bb294d',
  'target': 'bbc7da67-831d-5444-bc2c-b118639b8554',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '0316e58e-adf8-5a09-ace9-ad74dbdde04c',
  'target': '23f15ae7-d0f3-5375-97b6-7e022e74527f',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': 'a8f00715-2bd8-5c50-9e97-43e8a1dfc1fd',
  'target': '09c7e5b7-418b-58b4-b525-69a278408df2',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '06130775-2650-5939-a82b-694b6b93e923',
  'target': 'e4e938e0-b5dc-5b04-aeff-750a3441c8f2',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '57af7eb2-b514-5f33-8a6d-871813b1949a',
  'target': '5f2a0363-e6ad-5867-be4e-4dbe403e1ef4',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '284c805b-cb4d-5d19-9d41-ad0ee26f7862',
  'target': 'c019808a-0358-561e-9dba-9bcd7375e89b',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '794aa535-9297-5c22-8037-dd10cb3c8710',
  'target': 'e41f8971-522b-56c4-9945-e42816b71807',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '7cc3a510-14cb-58f9-bdd2-34b20bad1ca9',
  'target': 'bd9a30df-0ebb-527e-b15e-40a3e784eed3',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': 'f50d3355-4cbe-5ff7-9453-ce66650dd425',
  'target': 'e4a2a25c-5bf4-584b-91bc-799875ca19d3',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '13bd8d0e-2a3a-564a-9468-0ff8899ee5a8',
  'target': '242677cc-5cb6-5319-87c2-a4a2fb4dade6',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '05f030ad-036a-51c5-acaf-ae97fcb0cf34',
  'target': '9a425f73-5666-5c82-8f48-2d2867e499b5',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': 'e5d81810-4ff3-5054-a10b-35903c7c643c',
  'target': 'c3f47b3b-6ddd-5f23-95f6-c1bcf7fa5c17',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': 'd64f0c55-e165-561f-a313-f501cc8076ea',
  'target': '8642ced7-2f4c-5717-a485-7dcab8da3693',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '90549dd8-e3b4-5bb9-906f-528f95741439',
  'target': 'ff3d0f95-864e-55ec-84ba-ed9d72547c8d',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': 'f7b23683-b6a6-58bf-a737-37b7a0f7949e',
  'target': '583882f4-1e22-57f6-9acf-916eda6fc23e',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': 'b8625704-0aea-50b5-aed6-c113bcfe510b',
  'target': '8284db84-2917-5e69-aaab-cc44dd3574b5',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': 'a14bfb4a-d655-502f-865a-d3b6d8b97740',
  'target': 'f9137ceb-fffe-5fc9-9c8b-25e3d538915d',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '0139456d-952f-5f07-89d5-ceb492543e1b',
  'target': '8b6c9026-46ec-5b23-85d2-c029998b8e0e',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': 'ec483b4f-0ba3-52b4-b907-ff31e9683733',
  'target': 'd3bf1ed2-4d1a-5069-b2ae-225b1a3a51c0',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': 'cb5c99b0-98f2-5172-b14b-f11694b4b466',
  'target': 'ce9807ac-bb2a-510d-ba16-7312ce6132b2',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': 'b150ea1f-6174-5f85-86da-c2723578fc8e',
  'target': 'e032aa8c-f575-5877-a8af-719fb78fe880',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '07ff0b1e-782f-547f-a764-a5c72f200ab1',
  'target': 'acec03bc-82e0-51a4-925d-bdf2ac4b9bc0',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '777c2962-814c-58d9-9b7c-c46558d4371b',
  'target': '938b1d88-e2f6-56e8-8aa3-33b05c589393',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': 'b0883a6f-6432-5cc4-8c9c-2702fe1328da',
  'target': '063885ed-bfd6-57e4-a33b-286c43f4e91a',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': 'a8015877-22ca-5298-b2d8-f09e84a8cb81',
  'target': '2c7279d6-6b41-5631-a69d-b1fe9ba6d965',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': 'e4779ef1-1f2e-513d-9d94-98d667104e13',
  'target': 'c47c0d9b-2baa-5002-a1a7-e7fba3e10004',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '85594afd-9682-5e09-8595-e4e95157fdbf',
  'target': 'e13f11b5-acff-5796-b324-e789a1b2a5ee',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '95bc6276-da1a-5627-ae19-c86ae82370d6',
  'target': 'acefd181-9840-53d8-a191-a2dbf750d89e',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': 'c2fe8c01-b3c9-58f4-b79d-0bcb6f38fd8a',
  'target': '1bd5b003-03e2-5317-b27e-00e312140109',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': 'b08cee07-93a9-5f03-a5cd-1e403fa2ff24',
  'target': '6e829a3f-46a1-5303-822c-df6c4cb21bd3',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '5e99f949-5dc4-5bbb-90b5-a90040e20443',
  'target': '752858ab-88d8-5289-afbb-8bcacc2af543',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '987141c0-fa87-5d5c-826a-0da04956d352',
  'target': '96d40213-2a7a-5964-ba52-d6af10910dfa',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '3ef448d8-db3f-5d7d-9854-061164b4b02b',
  'target': 'b1cfc98a-5d22-59e9-9155-f17b4d8b09d4',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '3b76200e-28e4-5e7e-a570-251306127c20',
  'target': '8dd273b8-7533-5337-b774-8ac3b7980f87',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '162feb0e-3fb3-537c-be7a-b062c90107a6',
  'target': '315e74ee-2032-5abb-9393-c356be62c733',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '2fe25d17-0d10-5a41-b56f-e6790d8e1d47',
  'target': 'd380ef46-aabf-5f01-abf6-8f7d54e9b2a1',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': '8679eb10-7d60-51e6-8bd4-06d066bd9319',
  'target': 'd91a31e7-47ba-51cd-abe1-4ce46b198717',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': 'b19f8486-d1e0-5ae4-9168-227bf0c6f954',
  'target': '5d126426-f224-5de3-8283-3212b1299f43',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': 'f23456b6-c99b-5868-bab1-edc5f056feb7',
  'target': 'ce4e0186-8908-57e2-80ea-a3c7b24ad5b4',
  'relation': 'is_protein',
  'sab': 'HGNCUNIPROT'},
 {'source': 'a6cda91f-c1ec-5c4b-b8eb-2370ccf9c64a',

## ARCHS4

In [94]:
node_sabs['ARCHS4'] = node_sabs['ARCHS4'] + [
	'out/sab/LINCS.Compound.nodes.csv',
	'out/sab/MW.Metabolite.nodes.csv',
	'out/sab/IDGP.Compound.nodes.csv',
	'out/sab/IDGD.Compound.nodes.csv',
	'out/sab/HMAZ.Anatomy.nodes.csv',
	'out/sab/GLYCANS.Glytoucan.nodes.csv',
	'out/sab/PROTEOFORM.Glytoucan.nodes.csv'
	]

In [95]:
node_sabs['ARCHS4']

['out/sab/ARCHS4.Gene.nodes.csv',
 'out/sab/LINCS.Compound.nodes.csv',
 'out/sab/MW.Metabolite.nodes.csv',
 'out/sab/IDGP.Compound.nodes.csv',
 'out/sab/IDGD.Compound.nodes.csv',
 'out/sab/HMAZ.Anatomy.nodes.csv',
 'out/sab/GLYCANS.Glytoucan.nodes.csv',
 'out/sab/PROTEOFORM.Glytoucan.nodes.csv']

In [96]:
edge_pattern = "out/sab/(?P<SAB>.*)\.edges\.csv"
success = True
for filename in glob('out/sab/ARCHS4.edges.csv'):
	# GET ID TYPES
	sab = re.match(edge_pattern, filename).groupdict()['SAB']
	print(sab)
	df = pd.read_csv(filename, index_col=0)
	node_typer = {}
	for f in node_sabs[sab]:
		node_type = re.match(pattern, f).groupdict()['node_type']
		if len(node_type.split(" ")) > 1:
			node_type = "`%s`"%node_type
		with open(f) as o:
			csv_reader = csv.reader(o)
			for row in csv_reader:
				node_typer[row[0]] = node_type
	node_typer = pd.Series(node_typer)
	if len(df.index) != len(set(df.index)):
		df = df.reset_index()
		df = df[[i for i in df.columns if i != "index"]]
	# df["id"] = df.apply(lambda x: str(uuid5(NAMESPACE_URL, "%s_%s_%s_%s"%(x[0], x[2], x[1], x[3]))), axis=1)
	for relation in df.relation.unique():
		edges = []
		d = df[df.relation == relation].dropna(axis=1, how='all')
		source_type = "|".join(node_typer[d.source].unique())
		target_type = "|".join(node_typer[d.target].unique())
		print(source_type, target_type)
		meta = []
		for col in d.columns:
			if (col not in ["source", 'target']):
				meta.append("%s:row.%s"%(col, col))
		edges = list(d.to_dict(orient="index").values())
		print("Ingesting %d %s relation of %s"%(len(edges), relation, sab))
		meta = ",\n".join(meta)
		success = ingest_edges(relation, meta, source_type, target_type, edges)
		if not success:
			break
		if not success:
				break

ARCHS4
Gene|Metabolite Gene
Ingesting 209970 ARCHS4_coexpressed_genes relation of ARCHS4
Compound|Metabolite Gene
Ingesting 33410 ARCHS4_coexpressed_genes_LINCS_Up relation of ARCHS4
Compound Gene
Ingesting 33410 ARCHS4_coexpressed_genes_LINCS_Down relation of ARCHS4
Metabolite|Compound Gene
Ingesting 1560 ARCHS4_coexpressed_genes_MW relation of ARCHS4
Compound Gene
Ingesting 5140 ARCHS4_coexpressed_genes_IDG relation of ARCHS4
Anatomy Gene
Ingesting 700 ARCHS4_coexpressed_genes_HuBMAP relation of ARCHS4
Glytoucan Gene
Ingesting 3380 ARCHS4_coexpressed_genes_Glygen relation of ARCHS4

In [97]:
node_typer[df.source]

2bbf802a-884e-5db4-a738-c858576cc15f         Gene
2bbf802a-884e-5db4-a738-c858576cc15f         Gene
2bbf802a-884e-5db4-a738-c858576cc15f         Gene
2bbf802a-884e-5db4-a738-c858576cc15f         Gene
2bbf802a-884e-5db4-a738-c858576cc15f         Gene
                                          ...
d0b59ed3-95ae-5386-926c-1fc865074d45    Glytoucan
d0b59ed3-95ae-5386-926c-1fc865074d45    Glytoucan
d0b59ed3-95ae-5386-926c-1fc865074d45    Glytoucan
d0b59ed3-95ae-5386-926c-1fc865074d45    Glytoucan
d0b59ed3-95ae-5386-926c-1fc865074d45    Glytoucan
Length: 287570, dtype: object